apiVersion: apps/v1
kind: Deployment
metadata:
  name: partitioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partitioner
  template:
    metadata:
      labels:
        app: partitioner
    spec:
      containers:
        - name: partitioner
          image: "wrzontek/shortest_path_queries_partitioner:latest"
          command: ["python3", "-u", "main.py", "graphs/monaco.osm.gz"]
          args:
            - "--port=49998"
            - "--n_partitions=$(N_PARTITIONS)"
          ports:
            - containerPort: 49998
          envFrom:
            - configMapRef:
                name: worker-config
          env:
            - name: N_PARTITIONS
              valueFrom:
                configMapKeyRef:
                  name: worker-config
                  key: WORKER_REPLICAS
